source 'https://rubygems.org'

gem 'rails', '~> 4.0.0'
gem 'mongoid', git: 'git://github.com/mongoid/mongoid.git'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', '~> 0.3.20', require: false
end

group :development, :test do
  gem 'factory_girl_rails', '~> 4.2.1'
end

group :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'mongoid-rspec', '~> 1.8.2'
  gem 'faker', '~> 1.1.2'
end

gem 'rails-api', '~> 0.1.0'
gem 'api-versions', '~> 1.2.0'
gem 'chronic', '~> 0.9.1'
gem 'chronic_duration', '~> 0.10.2'
gem 'active_model_serializers', '~> 0.8.1'
gem 'dalli', '~> 2.6.4'
